#!/usr/bin/env julia

# Generate a mirror and write it to a file

using Mirrors

include("parser.jl")



function main(args=ARGS)
    # Parse
    argdict = parser(args, efield=false,
                     description="Generate a mirror and write it to a file")
    # Create and write mirror
    mirror = Mirror(argdict["radius"], argdict["nrings"], argdict["roughness_rms"],
                    argdict["roughness_sigma"])
    write(filename("mirror", argdict), mirror)
end



if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
